version: "3.8"
services:
  db:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_DATABASE: applestoredb
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - net
    restart: unless-stopped
  api:
    container_name: backendcontainer
    build: ./backend
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/applestoredb
    networks:
        - net
    depends_on:
        - db
    restart: unless-stopped
networks:
  net:
    driver: bridge

volumes:
  db: