services:
  db:
    container_name: applemart-db
    image: mysql
    environment:
      MYSQL_DATABASE: applemart
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: giabao
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - net
    restart: unless-stopped
  api:
    container_name: applemart-backend
    image: giabao144/applemart-api
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/applemart
    networks:
        - net
    depends_on:
        - db
    restart: unless-stopped
  frontend:
    container_name: applemart-frontend
    image: giabao144/applemart-react
    build:
      args:
        api_base_url: http://localhost:8088/api/v1
      context: frontend
    ports:
      - "3000:5173"
    depends_on:
      - api
    restart: unless-stopped
networks:
  net:
    driver: bridge

volumes:
  db: