server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/products/**, /api/v1/productItems/**, /api/v1/categories/**, /api/v1/variationOptions/**
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

