server:
  error:
    include-message: always
  port: 8081

spring:
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 123456
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: "0/zwN98/tLYa9/r6YD9C/8vg4w0wJ+AX6ALT2Pm2Fyjp3HHB3G4EYaMEjEshMOdb"

abstractapi:
  api-key: "5d963b2e40874c8c9502d54c02ac04d4"