server:
  error:
    include-message: always
  port: 8080

spring:
  config:
    import: env.properties
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ${JWT_SECRET_KEY}

abstractapi:
  api-key: ${ABSTRACTAPI_KEY}