server:
  error:
    include-message: always
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_KEY}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile
  config:
    import: env.properties
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret-key: ${JWT_SECRET_KEY}

abstractapi:
  api-key: ${ABSTRACTAPI_KEY}
