spring:
  profiles:
    active: dev
  application:
    name: cart
  config:
    import: optional:configserver:http://localhost:8000
  cloud:
    config:
      label: main
  kafka:
    bootstrap-servers: localhost:9094

