server:
  error:
    include-message: always
  port: 8082

spring:
  config:
    import: env.properties
  application:
    name: cart

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
    endpoint: http://zipkin:9411
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret-key: ${JWT_SECRET_KEY}
  
redis:
  host: redis
  port: 6379