global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'auth'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Auth Application'

  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8888' ]
        labels:
          application: 'ApiGateway Application'

  - job_name: 'order'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          application: 'Order Application'

  - job_name: 'product'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'Product Application'

  - job_name: 'cart'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: 'Cart Application'