server:
  error:
    include-message: always

spring:
  application:
    name: applestore
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/applestoredb
    username: root
    password: 123456
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off

logging:
  level:
    root: warn

api-prefix:
  path: api/v1
